name: Android CI

on:
  push:
    branches: [ main, develop, feature_*, release_*, hotfix_* ]
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        api-level: [26, 28]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-api${{ matrix.api-level }}-gradle-v6-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-api${{ matrix.api-level }}-gradle-v6-

    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Run instrumented tests with Gradle
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        disable-animations: true
        script: ./gradlew connectedCheck

    - name: Archive production artifacts
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: reports-api${{ matrix.api-level }}
        path: |
          app/build/reports
